gcloud:
  project: "bert-faqclass"

  database:
    type: "Firestore" #Google Cloud Firestore

    collections:
      knowledge_base:
        name: "KnowledgeBase"
      keywords:
        name: "Keywords"

  storage:
    prefix: "gs://"

    locations:
      checkpoints:
        bucket: "model_bert_faqclass"
        folders: "checkpoints/checkpoint"

      model_savings:
        bucket: "model_bert_faqclass"
        folders: "model"
########################################################################################################################
model:
  name: "model-bert-faqclass"
  version: "1.0.0"

  bert:
    url: "https://tfhub.dev/tensorflow/bert_multi_cased_L-12_H-768_A-12/3"
  preprocessor:
    url: "https://tfhub.dev/tensorflow/bert_multi_cased_preprocess/1"

  inputs:
    max_sequence_length: 128 # Max length of the input strings

  training:
    epochs: 500
    batch_size: 16

    load_checkpoints: False

    is_tensorboard_enabled: True
    is_checkpoints_enabled: True

    split:
      train: 0.6
      validation: 0.2
      test: 0.2
########################################################################################################################