version: 1
disable_existing_loggers: True

formatters:
    standard:
        format: "%(asctime)s %(levelname)-8s [%(filename)s:%(lineno)s - %(funcName)8s() ] %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        formatter: standard
        level: INFO
        stream: ext://sys.stdout
    info_rotating_file_handler:
        level: INFO
        formatter: standard
        class: logging.handlers.RotatingFileHandler
        filename: logs/info.log
        mode: a
        maxBytes: 1048576
    debug_rotating_file_handler:
        level: DEBUG
        formatter: standard
        class: logging.handlers.RotatingFileHandler
        filename: logs/debug.log
        mode: a
        maxBytes: 1048576
        backupCount: 10
    error_file_handler: 
        level: WARNING
        formatter: standard
        class: logging.FileHandler
        filename: logs/error.log
        mode: a

loggers:
    package:
        level: WARNING
        propagate: no
        handlers: [console, debug_rotating_file_handler, error_file_handler]
        
root:
    level: DEBUG
    handlers: [console, debug_rotating_file_handler, info_rotating_file_handler, error_file_handler]
